-- Create application user (runs as postgres superuser)
DO $$
BEGIN
  CREATE USER bipros WITH PASSWORD 'bipros_dev' CREATEDB;
EXCEPTION WHEN duplicate_object THEN
  RAISE NOTICE 'User bipros already exists';
END
$$;

-- Create database owned by bipros (if not using POSTGRES_DB)
GRANT ALL PRIVILEGES ON DATABASE bipros TO bipros;

-- Initialize PostgreSQL schemas per bounded context
CREATE SCHEMA IF NOT EXISTS project AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS activity AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS scheduling AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS resource AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS cost AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS evm AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS baseline AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS udf AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS risk AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS portfolio AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS contract AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS document AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS gis AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS permit AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS analytics AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS ai AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS site_ops AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS ncr AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS safety AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS dbs AUTHORIZATION bipros;
CREATE SCHEMA IF NOT EXISTS hds AUTHORIZATION bipros;
GRANT ALL ON SCHEMA hds TO bipros;
GRANT USAGE ON SCHEMA hds TO bipros;

-- pgvector extension (idempotent; installs into 'public' but is usable from any schema)
CREATE EXTENSION IF NOT EXISTS vector;

-- Grant public schema access
GRANT ALL ON SCHEMA public TO bipros;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO bipros;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO bipros;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO bipros;
